version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "user"
      POSTGRES_HOST: "localhost"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./init/insert_tables.sql:/docker-entrypoint-initdb.d/insert_tables.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - test

networks:
  test:
    name: test
